load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "nrfx_glue",
    hdrs = ["nrfx_glue.h"],
    includes = ["nRF5_SDK_17.0.0_9d13099/modules/nrfx/templates"],
)

cc_library(
    name = "nrfx_log",
    hdrs = ["nrfx_log.h"],
    includes = ["nRF5_SDK_17.0.0_9d13099/modules/nrfx/templates"],
)
