cc_library(
    name = "nfc_ble_oob_advdata",
    srcs = ["nfc_ble_oob_advdata.c"],
    hdrs = ["nfc_ble_oob_advdata.h"],
    includes = ["."],
    deps = [
        "//nRF5_SDK_17.0.0_9d13099/components/ble/common:ble_advdata",
        "//nRF5_SDK_17.0.0_9d13099/components/libraries/util:app_util",
        "//nRF5_SDK_17.0.0_9d13099/components/libraries/util:sdk_common",
        "//nRF5_SDK_17.0.0_9d13099/components/libraries/util:sdk_errors",
        "//nRF5_SDK_17.0.0_9d13099/components/nfc/ndef/connection_handover/ble_pair_msg:nfc_ble_pair_msg",
        "//nRF5_SDK_17.0.0_9d13099/components/nfc/ndef/connection_handover/common:nfc_ble_pair_common",
    ],
)
