load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "nrfx_usbd_errata",
    hdrs = ["nrfx_usbd_errata.h"],
    includes = ["nRF5_SDK_17.0.0_9d13099/modules/nrfx/drivers/src"],
)
