load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "nrfx_gppi",
    hdrs = ["nrfx_gppi.h"],
    includes = ["nRF5_SDK_17.0.0_9d13099/modules/nrfx/helpers"],
)
