load("@rules_cc//cc:defs.bzl", "cc_library")
package(default_visibility=["//visibility:public"])
cc_library(name="ble_ots", includes = ["."], deps = ["//nRF5_SDK_17.0.0_9d13099:d92f3c68-e77c-4cdd-a41b-c19271d7a345"])

cc_library(name="ble_ots_l2cap", includes = ["."], deps = ["//nRF5_SDK_17.0.0_9d13099:d92f3c68-e77c-4cdd-a41b-c19271d7a345"])

cc_library(name="ble_ots_oacp", includes = ["."], deps = ["//nRF5_SDK_17.0.0_9d13099:d92f3c68-e77c-4cdd-a41b-c19271d7a345"])

cc_library(name="ble_ots_object", includes = ["."], deps = ["//nRF5_SDK_17.0.0_9d13099:d92f3c68-e77c-4cdd-a41b-c19271d7a345"])

