cc_library(
    name = "nrf_strerror",
    srcs = ["nrf_strerror.c"],
    hdrs = ["nrf_strerror.h"],
    includes = ["."],
    deps = [
        "//nRF5_SDK_17.0.0_9d13099/components/libraries/util:sdk_common",
        "//nRF5_SDK_17.0.0_9d13099/components/libraries/util:sdk_errors",
    ],
)
