cc_library(
    name = "n5_starterkit",
    hdrs = ["n5_starterkit.h"],
    includes = ["."],
    deps = ["//nRF5_SDK_17.0.0_9d13099/modules/nrfx/hal:nrf_gpio"],
)

cc_library(
    name = "pca10040",
    hdrs = ["pca10040.h"],
    includes = ["."],
    deps = ["//nRF5_SDK_17.0.0_9d13099/modules/nrfx/hal:nrf_gpio"],
)

cc_library(
    name = "pca10000",
    hdrs = ["pca10000.h"],
    includes = ["."],
    deps = ["//nRF5_SDK_17.0.0_9d13099/modules/nrfx/hal:nrf_gpio"],
)

cc_library(
    name = "arduino_joystick_shield_v1a",
    hdrs = ["arduino_joystick_shield_v1a.h"],
    includes = ["."],
)

cc_library(
    name = "pca10100",
    hdrs = ["pca10100.h"],
    includes = ["."],
    deps = ["//nRF5_SDK_17.0.0_9d13099/modules/nrfx/hal:nrf_gpio"],
)

cc_library(
    name = "d52_starterkit",
    hdrs = ["d52_starterkit.h"],
    includes = ["."],
    deps = ["//nRF5_SDK_17.0.0_9d13099/modules/nrfx/hal:nrf_gpio"],
)

cc_library(
    name = "pca20020",
    hdrs = ["pca20020.h"],
    includes = ["."],
    deps = ["//nRF5_SDK_17.0.0_9d13099/modules/nrfx/hal:nrf_gpio"],
)

cc_library(
    name = "wt51822",
    hdrs = ["wt51822.h"],
    includes = ["."],
)

cc_library(
    name = "pca10036",
    hdrs = ["pca10036.h"],
    includes = ["."],
    deps = ["//nRF5_SDK_17.0.0_9d13099/modules/nrfx/hal:nrf_gpio"],
)

cc_library(
    name = "nrf6310",
    hdrs = ["nrf6310.h"],
    includes = ["."],
)

cc_library(
    name = "pca10031",
    hdrs = ["pca10031.h"],
    includes = ["."],
    deps = ["//nRF5_SDK_17.0.0_9d13099/modules/nrfx/hal:nrf_gpio"],
)

cc_library(
    name = "pca10001",
    hdrs = ["pca10001.h"],
    includes = ["."],
    deps = ["//nRF5_SDK_17.0.0_9d13099/modules/nrfx/hal:nrf_gpio"],
)

cc_library(
    name = "pca10003",
    hdrs = ["pca10003.h"],
    includes = ["."],
    deps = ["//nRF5_SDK_17.0.0_9d13099/modules/nrfx/hal:nrf_gpio"],
)

cc_library(
    name = "pca10059",
    hdrs = ["pca10059.h"],
    includes = ["."],
    deps = ["//nRF5_SDK_17.0.0_9d13099/modules/nrfx/hal:nrf_gpio"],
)

cc_library(
    name = "pca20006",
    hdrs = ["pca20006.h"],
    includes = ["."],
    deps = ["//nRF5_SDK_17.0.0_9d13099/modules/nrfx/hal:nrf_gpio"],
)

cc_library(
    name = "pca10056",
    hdrs = ["pca10056.h"],
    includes = ["."],
    deps = ["//nRF5_SDK_17.0.0_9d13099/modules/nrfx/hal:nrf_gpio"],
)

cc_library(
    name = "pca10112",
    hdrs = ["pca10112.h"],
    includes = ["."],
    deps = ["//nRF5_SDK_17.0.0_9d13099/modules/nrfx/hal:nrf_gpio"],
)

cc_library(
    name = "boards",
    srcs = ["boards.c"],
    hdrs = ["boards.h"],
    includes = ["."],
    deps = [
        ":arduino_primo",
        ":d52_starterkit",
        ":n5_starterkit",
        ":nrf6310",
        ":pca10000",
        ":pca10001",
        ":pca10003",
        ":pca10028",
        ":pca10031",
        ":pca10036",
        ":pca10040",
        ":pca10056",
        ":pca10059",
        ":pca10100",
        ":pca10112",
        ":pca20006",
        ":pca20020",
        ":wt51822",
        "//nRF5_SDK_17.0.0_9d13099/components/libraries/bootloader/dfu:nrf_dfu_trigger_usb",
        "//nRF5_SDK_17.0.0_9d13099/components/libraries/util:nordic_common",
        "//nRF5_SDK_17.0.0_9d13099/modules/nrfx/hal:nrf_gpio",
    ],
)

cc_library(
    name = "arduino_primo",
    hdrs = ["arduino_primo.h"],
    includes = ["."],
)

cc_library(
    name = "pca10028",
    hdrs = ["pca10028.h"],
    includes = ["."],
    deps = ["//nRF5_SDK_17.0.0_9d13099/modules/nrfx/hal:nrf_gpio"],
)
