load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = "//visibility:public")

cc_library(
    name = "nrfx_prs",
    srcs = ["nrfx_prs.c"],
    hdrs = ["nrfx_prs.h"],
    includes = ["."],
)
