cc_library(
    name = "conn_mw_ant",
    srcs = ["conn_mw_ant.c"],
    hdrs = ["conn_mw_ant.h"],
    includes = ["."],
    deps = [
        "TODO: user-provided",
        "//nRF5_SDK_17.0.0_9d13099/components/libraries/log:nrf_log_ctrl",
        "//nRF5_SDK_17.0.0_9d13099/components/serialization/common:ble_serialization",
        "//nRF5_SDK_17.0.0_9d13099/components/serialization/connectivity/codecs/ant/serializers:ant_conn",
    ],
)
