load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "ble_gls",
    includes = ["."],
    deps = ["//nRF5_SDK_17.0.0_9d13099:349c38ee-0551-4f0d-8466-82086bba7ea7"],
)

cc_library(
    name = "ble_gls_db",
    includes = ["."],
    deps = ["//nRF5_SDK_17.0.0_9d13099:349c38ee-0551-4f0d-8466-82086bba7ea7"],
)
