load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = "//visibility:public")

cc_library(
    name = "adns2080",
    srcs = ["adns2080.c"],
    hdrs = ["adns2080.h"],
    includes = ["."],
    deps = ["//nRF5_SDK_17.0.0_9d13099/components/drivers_nrf/sdio"],
)
