cc_library(
    name = "mcp4725",
    srcs = ["mcp4725.c"],
    hdrs = ["mcp4725.h"],
    includes = ["."],
    deps = [
        "//nRF5_SDK_17.0.0_9d13099/components/boards",
        "//nRF5_SDK_17.0.0_9d13099/components/libraries/delay:nrf_delay",
        "//nRF5_SDK_17.0.0_9d13099/components/libraries/util:app_util_platform",
        "//nRF5_SDK_17.0.0_9d13099/integration/nrfx/legacy:nrf_drv_twi",
    ],
)
