load("@rules_cc//cc:defs.bzl", "cc_library")

package(
    default_visibility = [
        "//nRF5_SDK_17.0.0_9d13099/examples/ble_central/ble_app_blinky_c:__subpackages__",
    ],
)

cc_library(
    name = "sdk_config",
    hdrs = ["sdk_config.h"],
    includes = ["."],
)
