load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "nrf_bitmask",
    hdrs = ["nrf_bitmask.h"],
    includes = ["nRF5_SDK_17.0.0_9d13099/modules/nrfx/drivers/include"],
)

cc_library(
    name = "nrfx_adc",
    hdrs = ["nrfx_adc.h"],
    includes = ["nRF5_SDK_17.0.0_9d13099/modules/nrfx/drivers/include"],
)

cc_library(
    name = "nrfx_clock",
    hdrs = ["nrfx_clock.h"],
    includes = ["nRF5_SDK_17.0.0_9d13099/modules/nrfx/drivers/include"],
)

cc_library(
    name = "nrfx_comp",
    hdrs = ["nrfx_comp.h"],
    includes = ["nRF5_SDK_17.0.0_9d13099/modules/nrfx/drivers/include"],
)

cc_library(
    name = "nrfx_dppi",
    hdrs = ["nrfx_dppi.h"],
    includes = ["nRF5_SDK_17.0.0_9d13099/modules/nrfx/drivers/include"],
)

cc_library(
    name = "nrfx_gpiote",
    hdrs = ["nrfx_gpiote.h"],
    includes = ["nRF5_SDK_17.0.0_9d13099/modules/nrfx/drivers/include"],
)

cc_library(
    name = "nrfx_i2s",
    hdrs = ["nrfx_i2s.h"],
    includes = ["nRF5_SDK_17.0.0_9d13099/modules/nrfx/drivers/include"],
)

cc_library(
    name = "nrfx_lpcomp",
    hdrs = ["nrfx_lpcomp.h"],
    includes = ["nRF5_SDK_17.0.0_9d13099/modules/nrfx/drivers/include"],
)

cc_library(
    name = "nrfx_nfct",
    hdrs = ["nrfx_nfct.h"],
    includes = ["nRF5_SDK_17.0.0_9d13099/modules/nrfx/drivers/include"],
)

cc_library(
    name = "nrfx_nvmc",
    hdrs = ["nrfx_nvmc.h"],
    includes = ["nRF5_SDK_17.0.0_9d13099/modules/nrfx/drivers/include"],
)

cc_library(
    name = "nrfx_pdm",
    hdrs = ["nrfx_pdm.h"],
    includes = ["nRF5_SDK_17.0.0_9d13099/modules/nrfx/drivers/include"],
)

cc_library(
    name = "nrfx_power",
    hdrs = ["nrfx_power.h"],
    includes = ["nRF5_SDK_17.0.0_9d13099/modules/nrfx/drivers/include"],
)

cc_library(
    name = "nrfx_power_clock",
    hdrs = ["nrfx_power_clock.h"],
    includes = ["nRF5_SDK_17.0.0_9d13099/modules/nrfx/drivers/include"],
)

cc_library(
    name = "nrfx_ppi",
    hdrs = ["nrfx_ppi.h"],
    includes = ["nRF5_SDK_17.0.0_9d13099/modules/nrfx/drivers/include"],
)

cc_library(
    name = "nrfx_pwm",
    hdrs = ["nrfx_pwm.h"],
    includes = ["nRF5_SDK_17.0.0_9d13099/modules/nrfx/drivers/include"],
)

cc_library(
    name = "nrfx_qdec",
    hdrs = ["nrfx_qdec.h"],
    includes = ["nRF5_SDK_17.0.0_9d13099/modules/nrfx/drivers/include"],
)

cc_library(
    name = "nrfx_qspi",
    hdrs = ["nrfx_qspi.h"],
    includes = ["nRF5_SDK_17.0.0_9d13099/modules/nrfx/drivers/include"],
)

cc_library(
    name = "nrfx_rng",
    hdrs = ["nrfx_rng.h"],
    includes = ["nRF5_SDK_17.0.0_9d13099/modules/nrfx/drivers/include"],
)

cc_library(
    name = "nrfx_rtc",
    hdrs = ["nrfx_rtc.h"],
    includes = ["nRF5_SDK_17.0.0_9d13099/modules/nrfx/drivers/include"],
)

cc_library(
    name = "nrfx_saadc",
    hdrs = ["nrfx_saadc.h"],
    includes = ["nRF5_SDK_17.0.0_9d13099/modules/nrfx/drivers/include"],
    deps = [":nrfx_saadc_v2"],
)

cc_library(
    name = "nrfx_saadc_v2",
    hdrs = ["nrfx_saadc_v2.h"],
    includes = ["nRF5_SDK_17.0.0_9d13099/modules/nrfx/drivers/include"],
)

cc_library(
    name = "nrfx_spi",
    hdrs = ["nrfx_spi.h"],
    includes = ["nRF5_SDK_17.0.0_9d13099/modules/nrfx/drivers/include"],
)

cc_library(
    name = "nrfx_spim",
    hdrs = ["nrfx_spim.h"],
    includes = ["nRF5_SDK_17.0.0_9d13099/modules/nrfx/drivers/include"],
)

cc_library(
    name = "nrfx_spis",
    hdrs = ["nrfx_spis.h"],
    includes = ["nRF5_SDK_17.0.0_9d13099/modules/nrfx/drivers/include"],
)

cc_library(
    name = "nrfx_swi",
    hdrs = ["nrfx_swi.h"],
    includes = ["nRF5_SDK_17.0.0_9d13099/modules/nrfx/drivers/include"],
)

cc_library(
    name = "nrfx_systick",
    hdrs = ["nrfx_systick.h"],
    includes = ["nRF5_SDK_17.0.0_9d13099/modules/nrfx/drivers/include"],
)

cc_library(
    name = "nrfx_temp",
    hdrs = ["nrfx_temp.h"],
    includes = ["nRF5_SDK_17.0.0_9d13099/modules/nrfx/drivers/include"],
)

cc_library(
    name = "nrfx_timer",
    hdrs = ["nrfx_timer.h"],
    includes = ["nRF5_SDK_17.0.0_9d13099/modules/nrfx/drivers/include"],
)

cc_library(
    name = "nrfx_twi",
    hdrs = ["nrfx_twi.h"],
    includes = ["nRF5_SDK_17.0.0_9d13099/modules/nrfx/drivers/include"],
)

cc_library(
    name = "nrfx_twi_twim",
    hdrs = ["nrfx_twi_twim.h"],
    includes = ["nRF5_SDK_17.0.0_9d13099/modules/nrfx/drivers/include"],
)

cc_library(
    name = "nrfx_twim",
    hdrs = ["nrfx_twim.h"],
    includes = ["nRF5_SDK_17.0.0_9d13099/modules/nrfx/drivers/include"],
)

cc_library(
    name = "nrfx_twis",
    hdrs = ["nrfx_twis.h"],
    includes = ["nRF5_SDK_17.0.0_9d13099/modules/nrfx/drivers/include"],
)

cc_library(
    name = "nrfx_uart",
    hdrs = ["nrfx_uart.h"],
    includes = ["nRF5_SDK_17.0.0_9d13099/modules/nrfx/drivers/include"],
)

cc_library(
    name = "nrfx_uarte",
    hdrs = ["nrfx_uarte.h"],
    includes = ["nRF5_SDK_17.0.0_9d13099/modules/nrfx/drivers/include"],
)

cc_library(
    name = "nrfx_usbd",
    hdrs = ["nrfx_usbd.h"],
    includes = ["nRF5_SDK_17.0.0_9d13099/modules/nrfx/drivers/include"],
)

cc_library(
    name = "nrfx_wdt",
    hdrs = ["nrfx_wdt.h"],
    includes = ["nRF5_SDK_17.0.0_9d13099/modules/nrfx/drivers/include"],
)
