load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "nrfx_config",
    hdrs = ["nrfx_config.h"],
    includes = ["nRF5_SDK_17.0.0_9d13099/modules/nrfx/templates/nRF9160"],
)
