load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "nfc_le_oob_rec",
    includes = ["."],
    deps = ["//nRF5_SDK_17.0.0_9d13099:cbef4a45-ffa2-49c6-9495-92a8dfde20c3"],
)
