cc_library(
    name = "nrf_twi_sensor",
    srcs = ["nrf_twi_sensor.c"],
    hdrs = ["nrf_twi_sensor.h"],
    includes = ["."],
    deps = [
        "//nRF5_SDK_17.0.0_9d13099/components/libraries/balloc:nrf_balloc",
        "//nRF5_SDK_17.0.0_9d13099/components/libraries/log:nrf_log",
        "//nRF5_SDK_17.0.0_9d13099/components/libraries/twi_mngr:nrf_twi_mngr",
    ],
)
