load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = "//visibility:public")

cc_library(
    name = "nrfx_common",
    hdrs = ["nrfx_common.h"],
    includes = ["."],
)

cc_library(
    name = "nrfx_errors",
    hdrs = ["nrfx_errors.h"],
    includes = ["."],
)
