load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "nrfx_common",
    hdrs = ["nrfx_common.h"],
    includes = ["nRF5_SDK_17.0.0_9d13099/modules/nrfx/drivers"],
)

cc_library(
    name = "nrfx_errors",
    hdrs = ["nrfx_errors.h"],
    includes = ["nRF5_SDK_17.0.0_9d13099/modules/nrfx/drivers"],
)
