load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = "//visibility:public")

cc_library(name = "nrfbazelify_empty_remap")

label_attr(
    name = "es_app_config_remap",
    build_setting_default = "//nRF5_SDK_17.0.0_9d13099:nrfbazelify_empty_remap",
)

label_attr(
    name = "nrf_crypto_allocator_remap",
    build_setting_default = "//nRF5_SDK_17.0.0_9d13099:nrfbazelify_empty_remap",
)

label_attr(
    name = "nrf_drv_config_remap",
    build_setting_default = "//nRF5_SDK_17.0.0_9d13099:nrfbazelify_empty_remap",
)

label_attr(
    name = "sdk_config_remap",
    build_setting_default = "//nRF5_SDK_17.0.0_9d13099:nrfbazelify_empty_remap",
)
