load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = "//visibility:public")

cc_library(
    name = "nrfx_config",
    hdrs = ["nrfx_config.h"],
    includes = ["."],
)

cc_library(
    name = "nrfx_glue",
    hdrs = ["nrfx_glue.h"],
    includes = ["."],
)

cc_library(
    name = "nrfx_log",
    hdrs = ["nrfx_log.h"],
    includes = ["."],
)
