cc_library(
    name = "nfc_platform",
    srcs = ["nfc_platform.c"],
    hdrs = ["nfc_platform.h"],
    includes = ["."],
    deps = [
        "//nRF5_SDK_17.0.0_9d13099/components/libraries/log:nrf_log",
        "//nRF5_SDK_17.0.0_9d13099/components/libraries/util:sdk_common",
        "//nRF5_SDK_17.0.0_9d13099/integration/nrfx/legacy:nrf_drv_clock",
        "//nRF5_SDK_17.0.0_9d13099/modules/nrfx/drivers/include:nrfx_nfct",
    ],
)
