load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = "//visibility:public")

cc_library(
    name = "twi_master_config",
    hdrs = ["twi_master_config.h"],
    includes = ["."],
)
