load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "nrf_delay",
    hdrs = ["nrf_delay.h"],
    includes = ["nRF5_SDK_17.0.0_9d13099/components/libraries/delay"],
)
