load("@rules_cc//cc:defs.bzl", "cc_library")
package(default_visibility=["//visibility:public"])
cc_library(name="cherry8x16", srcs = ["cherry8x16.c"], hdrs = ["cherry8x16.h"], includes = ["."], deps = ["//nRF5_SDK_17.0.0_9d13099/modules/nrfx/mdk:nrf"])

