cc_library(
    name = "app_sdcard",
    srcs = ["app_sdcard.c"],
    hdrs = ["app_sdcard.h"],
    includes = ["."],
    deps = [
        "TODO: user-provided",
        "//nRF5_SDK_17.0.0_9d13099/components/libraries/util:app_error",
        "//nRF5_SDK_17.0.0_9d13099/components/libraries/util:app_util_platform",
        "//nRF5_SDK_17.0.0_9d13099/components/libraries/util:nrf_assert",
        "//nRF5_SDK_17.0.0_9d13099/external/protothreads:nrf_pt",
        "//nRF5_SDK_17.0.0_9d13099/integration/nrfx/legacy:nrf_drv_spi",
        "//nRF5_SDK_17.0.0_9d13099/modules/nrfx/hal:nrf_gpio",
    ],
)
