load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "ancs_app_attr_get",
    includes = ["."],
    deps = ["//nRF5_SDK_17.0.0_9d13099:783d6df2-1282-4c98-8c0c-b0a007eefb08"],
)

cc_library(
    name = "ancs_attr_parser",
    includes = ["."],
    deps = ["//nRF5_SDK_17.0.0_9d13099:783d6df2-1282-4c98-8c0c-b0a007eefb08"],
)

cc_library(
    name = "nrf_ble_ancs_c",
    includes = ["."],
    deps = ["//nRF5_SDK_17.0.0_9d13099:783d6df2-1282-4c98-8c0c-b0a007eefb08"],
)
