load("@rules_cc//cc:defs.bzl", "cc_library")
package(default_visibility=["//visibility:public"])
cc_library(name="cgms_db", includes = ["."], deps = ["//nRF5_SDK_17.0.0_9d13099:99936464-8e73-4d4c-9d6b-dfd1ba4602a6"])

cc_library(name="cgms_meas", includes = ["."], deps = ["//nRF5_SDK_17.0.0_9d13099:99936464-8e73-4d4c-9d6b-dfd1ba4602a6"])

cc_library(name="cgms_racp", includes = ["."], deps = ["//nRF5_SDK_17.0.0_9d13099:99936464-8e73-4d4c-9d6b-dfd1ba4602a6"])

cc_library(name="cgms_socp", includes = ["."], deps = ["//nRF5_SDK_17.0.0_9d13099:99936464-8e73-4d4c-9d6b-dfd1ba4602a6"])

cc_library(name="cgms_sst", includes = ["."], deps = ["//nRF5_SDK_17.0.0_9d13099:99936464-8e73-4d4c-9d6b-dfd1ba4602a6"])

cc_library(name="nrf_ble_cgms", includes = ["."], deps = ["//nRF5_SDK_17.0.0_9d13099:99936464-8e73-4d4c-9d6b-dfd1ba4602a6"])

