load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "nrfx_atomic",
    srcs = ["nrfx_atomic.c"],
    hdrs = ["nrfx_atomic.h"],
    includes = ["nRF5_SDK_17.0.0_9d13099/modules/nrfx/soc"],
    deps = [":nrfx_atomic_internal"],
)

cc_library(
    name = "nrfx_atomic_internal",
    hdrs = ["nrfx_atomic_internal.h"],
    includes = ["nRF5_SDK_17.0.0_9d13099/modules/nrfx/soc"],
)

cc_library(
    name = "nrfx_coredep",
    hdrs = ["nrfx_coredep.h"],
    includes = ["nRF5_SDK_17.0.0_9d13099/modules/nrfx/soc"],
)

cc_library(
    name = "nrfx_irqs",
    hdrs = ["nrfx_irqs.h"],
    includes = ["nRF5_SDK_17.0.0_9d13099/modules/nrfx/soc"],
)

cc_library(
    name = "nrfx_irqs_nrf51",
    hdrs = ["nrfx_irqs_nrf51.h"],
    includes = ["nRF5_SDK_17.0.0_9d13099/modules/nrfx/soc"],
)

cc_library(
    name = "nrfx_irqs_nrf52810",
    hdrs = ["nrfx_irqs_nrf52810.h"],
    includes = ["nRF5_SDK_17.0.0_9d13099/modules/nrfx/soc"],
)

cc_library(
    name = "nrfx_irqs_nrf52811",
    hdrs = ["nrfx_irqs_nrf52811.h"],
    includes = ["nRF5_SDK_17.0.0_9d13099/modules/nrfx/soc"],
)

cc_library(
    name = "nrfx_irqs_nrf52820",
    hdrs = ["nrfx_irqs_nrf52820.h"],
    includes = ["nRF5_SDK_17.0.0_9d13099/modules/nrfx/soc"],
)

cc_library(
    name = "nrfx_irqs_nrf52832",
    hdrs = ["nrfx_irqs_nrf52832.h"],
    includes = ["nRF5_SDK_17.0.0_9d13099/modules/nrfx/soc"],
)

cc_library(
    name = "nrfx_irqs_nrf52833",
    hdrs = ["nrfx_irqs_nrf52833.h"],
    includes = ["nRF5_SDK_17.0.0_9d13099/modules/nrfx/soc"],
)

cc_library(
    name = "nrfx_irqs_nrf52840",
    hdrs = ["nrfx_irqs_nrf52840.h"],
    includes = ["nRF5_SDK_17.0.0_9d13099/modules/nrfx/soc"],
)

cc_library(
    name = "nrfx_irqs_nrf9160",
    hdrs = ["nrfx_irqs_nrf9160.h"],
    includes = ["nRF5_SDK_17.0.0_9d13099/modules/nrfx/soc"],
)
