load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "ser_conn_cmd_decoder",
    includes = ["."],
    deps = ["//nRF5_SDK_17.0.0_9d13099:1201b872-0091-4365-bf21-61f1e195a1d2"],
)

cc_library(
    name = "ser_conn_dtm_cmd_decoder",
    includes = ["."],
    deps = ["//nRF5_SDK_17.0.0_9d13099:1201b872-0091-4365-bf21-61f1e195a1d2"],
)

cc_library(
    name = "ser_conn_event_encoder",
    includes = ["."],
    deps = ["//nRF5_SDK_17.0.0_9d13099:1201b872-0091-4365-bf21-61f1e195a1d2"],
)

cc_library(
    name = "ser_conn_handlers",
    includes = ["."],
    deps = ["//nRF5_SDK_17.0.0_9d13099:1201b872-0091-4365-bf21-61f1e195a1d2"],
)

cc_library(
    name = "ser_conn_pkt_decoder",
    includes = ["."],
    deps = ["//nRF5_SDK_17.0.0_9d13099:1201b872-0091-4365-bf21-61f1e195a1d2"],
)

cc_library(
    name = "ser_conn_reset_cmd_decoder",
    includes = ["."],
    deps = ["//nRF5_SDK_17.0.0_9d13099:1201b872-0091-4365-bf21-61f1e195a1d2"],
)
