load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "sensorsim",
    srcs = ["sensorsim.c"],
    hdrs = ["sensorsim.h"],
    includes = ["nRF5_SDK_17.0.0_9d13099/components/libraries/sensorsim"],
)
