load("@rules_cc//cc:defs.bzl", "cc_library")
package(default_visibility=["//visibility:public"])
cc_library(name="nfc_ndef_record", srcs = ["nfc_ndef_record.c"], hdrs = ["nfc_ndef_record.h"], includes = ["."], deps = ["//nRF5_SDK_17.0.0_9d13099/components/libraries/util:app_util", "//nRF5_SDK_17.0.0_9d13099/components/libraries/util:nordic_common", "//nRF5_SDK_17.0.0_9d13099/components/libraries/util:sdk_errors", "//nRF5_SDK_17.0.0_9d13099/modules/nrfx/mdk:compiler_abstraction", "//nRF5_SDK_17.0.0_9d13099:fd0248f6-a546-4781-bd6c-1ef963497768", "//nRF5_SDK_17.0.0_9d13099:sdk_config_remap"])

