load("@rules_cc//cc:defs.bzl", "cc_library")
package(default_visibility=["//visibility:public"])
cc_library(name="nfc_ble_pair_common", srcs = ["nfc_ble_pair_common.c"], hdrs = ["nfc_ble_pair_common.h"], includes = ["."], deps = ["//nRF5_SDK_17.0.0_9d13099/components/ble/common:ble_advdata", "//nRF5_SDK_17.0.0_9d13099:100f0197-983a-4344-b22d-2887b0fffc9d"])

