load("@rules_cc//cc:defs.bzl", "cc_library")
package(default_visibility=["//visibility:public"])
cc_library(name="nrf_ble_ots_c", includes = ["."], deps = ["//nRF5_SDK_17.0.0_9d13099:9c2485b5-9408-424f-83e6-604f362a1048"])

cc_library(name="nrf_ble_ots_c_l2cap", includes = ["."], deps = ["//nRF5_SDK_17.0.0_9d13099:9c2485b5-9408-424f-83e6-604f362a1048"])

cc_library(name="nrf_ble_ots_c_oacp", includes = ["."], deps = ["//nRF5_SDK_17.0.0_9d13099:9c2485b5-9408-424f-83e6-604f362a1048"])

